export const GET_SNIPPET = 'GET_SNIPPET'
export const ADD_SNIPPET = 'ADD_SNIPPET'
export const EDIT_SNIPPET = 'EDIT_SNIPPET'
export const DELETE_SNIPPET = 'DELETE_SNIPPET'
export const SET_ACTIVE_SNIPPET = 'SET_ACTIVE_SNIPPET'
export const GET_SNIPPETS = 'GET_SNIPPETS'
export const SET_SNIPPETS = 'SET_SNIPPETS'

export const SET_ACTIVE_OPTION = 'SET_ACTIVE_OPTION'
